<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>4893a0f8-0b77-46e9-8f3b-b91a16e0543a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Estée Lauder Companies Logo&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='headerWrapper']/section/section/article[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d7fe4c63-38af-4c35-8bc0-ce91fee04d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.elcompanies.com/images/e/estee-lauder-companies/universal/logo/0-estee_lauder-logo-white-thick-660.png</value>
      <webElementGuid>b2c3f4e7-69ea-4837-bc6e-81e901197783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Estée Lauder Companies Logo</value>
      <webElementGuid>8f3d1382-4e46-44e5-b83c-77cc1489f9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>660</value>
      <webElementGuid>f8acd160-3d1e-413f-a41e-42bf34009fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>46</value>
      <webElementGuid>f86631a4-eaee-42f4-bec4-6f1e1c81295f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerWrapper&quot;)/section[@class=&quot;headerWrapperInner container-fluid&quot;]/section[@class=&quot;header-ticker-logo-search row&quot;]/article[@class=&quot;header-logo col-md-4 col-sm-offset-2 col-md-offset-0 col-sm-6 col-xs-offset-0 col-xs-8&quot;]/img[1]</value>
      <webElementGuid>9dac0e4f-3616-408c-a579-664d0a674df1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='headerWrapper']/section/section/article[2]/img</value>
      <webElementGuid>787989e7-9912-4342-ab26-ce7e12317458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Estée Lauder Companies Logo']</value>
      <webElementGuid>fb2566c2-9d0d-4d07-87fd-a6f8d30066e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>61bf1a73-792b-4257-b6d0-5d2b2a7fd164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.elcompanies.com/images/e/estee-lauder-companies/universal/logo/0-estee_lauder-logo-white-thick-660.png' and @alt = 'Estée Lauder Companies Logo']</value>
      <webElementGuid>8fae7c2f-87e2-4c9b-9ff9-f6703e288e66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
