<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Apply</name>
   <tag></tag>
   <elementGuidId>e21939f2-b42e-4f28-a3b2-e7e1052907d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-apply-level2 > a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-apply-level2']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e5289d6b-13bf-42ae-b6d5-664ca868d1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>84d00832-6981-4508-8510-08acd72bc30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-apply-level2&quot;)/a[1]/span[1]</value>
      <webElementGuid>a3b5dfa2-b969-49d6-95d4-b5c5e2b1f006</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-apply-level2']/a/span</value>
      <webElementGuid>8428c45c-5f64-4942-b1a6-34d8de5ef973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full-Time Programs'])[2]/following::span[1]</value>
      <webElementGuid>bf96f785-0fca-41c8-ab00-4385bc1a66dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Internships'])[2]/following::span[2]</value>
      <webElementGuid>d60e9b7b-6076-4e72-b5ed-b46865789b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Benefits'])[2]/preceding::span[1]</value>
      <webElementGuid>8ffbabd5-e4d9-4a8f-b4ed-b241bafbc600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News &amp; Media'])[3]/preceding::span[2]</value>
      <webElementGuid>ae28b2c7-3c31-4cfb-b9b0-5d92ce784e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li/div[5]/ul/li/a/span</value>
      <webElementGuid>83cda6e6-7928-4d41-8ad5-0fe5b3db3756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Apply' or . = 'Apply')]</value>
      <webElementGuid>e3f268ad-3da1-4baa-a8bc-b63e3949bddb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
