<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Contact Us</name>
   <tag></tag>
   <elementGuidId>891d94af-8b13-451d-a8c2-f948220bdcac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-contact-us-level2 > a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-contact-us-level2']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>89da6b61-2e4a-426c-8eda-0fe31ea5b45c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact Us</value>
      <webElementGuid>25f93cb6-3644-428b-987d-96f285e0940b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-contact-us-level2&quot;)/a[1]/span[1]</value>
      <webElementGuid>451c1609-fdae-4684-b4cd-1a9d61724ec5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-contact-us-level2']/a/span</value>
      <webElementGuid>ba0136fe-8829-4161-80b0-f0d4bcc1aec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resources &amp; Reports'])[2]/following::span[1]</value>
      <webElementGuid>591a6ac3-c584-4239-8328-1ae4d283c22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Executive Profiles'])[2]/following::span[2]</value>
      <webElementGuid>7043f372-7aee-4446-bcba-248255847197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Alerts'])[2]/preceding::span[1]</value>
      <webElementGuid>6f959286-1faa-42ff-96b1-9de82841f5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investors'])[3]/preceding::span[2]</value>
      <webElementGuid>29ad01c4-64b0-4c36-8496-09cccec53966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li/div[5]/ul/li/a/span</value>
      <webElementGuid>a7ba28ae-1c45-4cec-9b2d-b7bd45c39293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Contact Us' or . = 'Contact Us')]</value>
      <webElementGuid>02ebbec9-74fa-45c2-aec5-5f451bb801c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
