<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_News  Media</name>
   <tag></tag>
   <elementGuidId>03bf0478-a0a2-4c8e-b114-1a8c850f79c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.focusA > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-news-and-media-level1']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4ac790af-4999-4f69-8bcd-365e9847238c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7934dcb7-bcbc-40d2-91e0-88a22385587d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>News &amp; Media</value>
      <webElementGuid>2f6ab4b2-6d44-4cfa-a7f5-824d3597eaec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-news-and-media-level1&quot;)/a[@class=&quot;focusA&quot;]/span[1]</value>
      <webElementGuid>b8735802-8275-45c3-8b87-85a00eba37ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-news-and-media-level1']/a/span</value>
      <webElementGuid>e66a1154-2a46-422d-ae81-6252e787937f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Benefits'])[2]/following::span[1]</value>
      <webElementGuid>492a806c-54d1-4fa3-813c-22f54d494383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[3]/following::span[2]</value>
      <webElementGuid>9f6ace57-f65a-4a6a-937c-56989114bd42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close'])[5]/preceding::span[1]</value>
      <webElementGuid>e53ed992-909e-49ec-8273-66b2e239dc18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News &amp; Media Overview'])[1]/preceding::span[3]</value>
      <webElementGuid>9fbef197-c3f7-461a-9354-1c7707d988eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[5]/a/span</value>
      <webElementGuid>d534a22c-49bb-472f-9a52-6d6272ab1283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'News &amp; Media' or . = 'News &amp; Media')]</value>
      <webElementGuid>e6fb1449-0f7b-4970-8dff-280c0b6bd04e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
