<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_NOT THIS TIME</name>
   <tag></tag>
   <elementGuidId>97fa6431-3eba-4233-a57b-6c241ae99c04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.survey-no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='JSQuestion']/div/div[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b2ffc01f-78e2-485c-af95-4688f6775546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>survey-no</value>
      <webElementGuid>84406b32-4ba9-4adc-b94f-b9e97689d3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6299d6bd-b616-48d0-9607-d29526da0c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>84816ca9-91d1-4d80-a26b-531c1d701c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NOT THIS TIME</value>
      <webElementGuid>f2d5bacd-bdc9-418b-afac-68514a766020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JSQuestion&quot;)/div[@class=&quot;survey-inner&quot;]/div[@class=&quot;survey-buttons&quot;]/a[@class=&quot;survey-no&quot;]</value>
      <webElementGuid>56b33d0f-f21a-4df7-bf86-929c5d73f404</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='JSQuestion']/div/div[4]/a</value>
      <webElementGuid>1a3fc78a-968d-4ed2-9ae5-e94d62a7e43c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'NOT THIS TIME')]</value>
      <webElementGuid>a24967e6-222f-4984-9a70-c448cc4b38bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ELCompanies Survey Invitation - press escape to dismiss'])[1]/following::a[1]</value>
      <webElementGuid>efdc0709-33f4-4f5a-afdf-ca194edd58da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm My Choices'])[1]/following::a[2]</value>
      <webElementGuid>776bf916-25f8-4759-b44c-2757378f60d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Survey opens in new window)'])[1]/preceding::a[1]</value>
      <webElementGuid>8ee87e52-dabe-46ce-9d98-9be3f6ae272b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NOT THIS TIME']/parent::*</value>
      <webElementGuid>09112492-584a-40c5-8a2b-cb0350e79148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[96]</value>
      <webElementGuid>d83b727d-3655-40c9-a1b0-082c7826a5ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>e96548b0-38ec-4ef4-975b-fe6f20bc57e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'NOT THIS TIME' or . = 'NOT THIS TIME')]</value>
      <webElementGuid>87963e37-0ebb-45c1-a8e7-8ad97485eea6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
