<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Contact Us</name>
   <tag></tag>
   <elementGuidId>fad9e6b6-5311-4fed-89b1-5c33ea6cfd05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-contact-us-level2 > a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-contact-us-level2']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e005c7ba-e11d-4a37-9397-384e4ad92219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact Us</value>
      <webElementGuid>e3231282-31f9-4026-a529-4e1bb1c5414c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-contact-us-level2&quot;)/a[1]/span[1]</value>
      <webElementGuid>bc90eb77-a7ed-40e5-8b70-5cb1fb2e62c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-contact-us-level2']/a/span</value>
      <webElementGuid>98a506cb-b7f2-4ea8-834f-8a2628fce14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resources &amp; Reports'])[2]/following::span[1]</value>
      <webElementGuid>f2450994-897c-48fc-8cd7-48a0eb3c4a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Executive Profiles'])[2]/following::span[2]</value>
      <webElementGuid>0853aed3-8f7a-417c-95ae-eee564969dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Alerts'])[2]/preceding::span[1]</value>
      <webElementGuid>cc10d9a1-d520-4e62-a34c-3454394e2896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investors'])[3]/preceding::span[2]</value>
      <webElementGuid>94cb2ca2-26ce-4642-8e1b-512724baf5e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li/div[5]/ul/li/a/span</value>
      <webElementGuid>70bf21f2-8b5c-4f67-859e-4d66d23cab27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Contact Us' or . = 'Contact Us')]</value>
      <webElementGuid>758066f7-6fb2-4c4e-af47-6a80eb7f867c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
