<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_NOT THIS TIME</name>
   <tag></tag>
   <elementGuidId>ab9c1cf0-e3ec-419a-a722-83ed9107b06a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.survey-no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='JSQuestion']/div/div[4]/a</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#' and (text() = 'NOT THIS TIME' or . = 'NOT THIS TIME')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e2827a77-f6d1-4faf-953f-55121b23a208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>survey-no</value>
      <webElementGuid>06f5ecca-e5df-4919-9871-fe938f7e33ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5241ca30-050d-481a-be98-d9b502040825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2521d93a-028b-4804-af14-5b0d45d2cb66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NOT THIS TIME</value>
      <webElementGuid>e0d812c3-fd33-4419-b255-49921cccd792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JSQuestion&quot;)/div[@class=&quot;survey-inner&quot;]/div[@class=&quot;survey-buttons&quot;]/a[@class=&quot;survey-no&quot;]</value>
      <webElementGuid>a1edec2e-4baf-41c1-b5b1-80f7dfaf20e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='JSQuestion']/div/div[4]/a</value>
      <webElementGuid>ede69368-c3ca-4ba3-a6ae-b398fca0152b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'NOT THIS TIME')]</value>
      <webElementGuid>2a4c9683-bec4-4baa-ad37-5cea5091bd0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ELCompanies Survey Invitation - press escape to dismiss'])[1]/following::a[1]</value>
      <webElementGuid>e336849a-4600-44cd-81f3-9d9136227f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm My Choices'])[1]/following::a[2]</value>
      <webElementGuid>1e1efa0a-cdc1-4fd1-9526-e732e81c1f38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Survey opens in new window)'])[1]/preceding::a[1]</value>
      <webElementGuid>b5c0e143-b10a-4777-9071-a06f40f4a273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NOT THIS TIME']/parent::*</value>
      <webElementGuid>803e362a-b4a5-4d1e-b0e9-3814b65303ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[139]</value>
      <webElementGuid>8a2c46f6-d3c3-4d1c-8ab0-a2a0b9ecc26f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>9297d74e-f92e-4fb3-a5b5-888d87cd173d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'NOT THIS TIME' or . = 'NOT THIS TIME')]</value>
      <webElementGuid>5ead1ca1-d678-4f62-bb7a-9fde29b43e18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
