<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select</name>
   <tag></tag>
   <elementGuidId>559c62f5-1698-4486-a874-52f0e73091e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.selection-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='dialog-box']/section/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e448548c-c5e5-4dbf-a080-2857d079db26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>660bdd08-3b40-4898-a9ad-73f8c06d42f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selection-label</value>
      <webElementGuid>36bcd3de-d277-4f13-b8ea-dc1562521732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select* </value>
      <webElementGuid>abcc3588-b5fc-4f8c-8639-25d5cb2cbffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialog-box&quot;)/section[@class=&quot;hidden-section&quot;]/div[@class=&quot;selection-section&quot;]/div[@class=&quot;selection-wrapper&quot;]/a[@class=&quot;selection-label&quot;]</value>
      <webElementGuid>3667566f-3d49-4d7b-94c1-1cbf7ed4d77a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='dialog-box']/section/div/div/a</value>
      <webElementGuid>9b3c66d7-92f8-4b91-8237-ecc57121d2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Form'])[1]/following::a[1]</value>
      <webElementGuid>70cd6190-91e9-47bf-abee-cee12fd7fcbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::a[7]</value>
      <webElementGuid>892afda5-85f2-40e0-ba05-1a1826461e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:;')]</value>
      <webElementGuid>f3836dbb-c04b-4850-8f5f-f280d101e36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>87acb3bf-5626-4d04-b5d6-bae6605734e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Select* ' or . = 'Select* ')]</value>
      <webElementGuid>1c75368e-98f2-44ef-8eb4-c5317b441431</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
