<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Employee Query_form-frame</name>
   <tag></tag>
   <elementGuidId>3532ae3e-eb21-49c4-8f92-3b4d984ce223</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.form-frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='dialog-box']/section[2]/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>29b913fc-a97e-460b-ad4c-78c7d4f24cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-frame</value>
      <webElementGuid>d5589179-1de2-4078-a9b9-790777aa05ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/en/news-and-media/contact-us/forms/employees</value>
      <webElementGuid>3a06ba72-551c-4669-9a2a-64aa5f804123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Contact form</value>
      <webElementGuid>5b01075a-25b0-4d53-86df-681c45cb6c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1032</value>
      <webElementGuid>ea53852f-339a-4bf0-8081-cbb9f67b8b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialog-box&quot;)/section[@class=&quot;form-section&quot;]/iframe[@class=&quot;form-frame&quot;]</value>
      <webElementGuid>212f1419-731f-4c3f-899e-2576e072cd74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='dialog-box']/section[2]/iframe</value>
      <webElementGuid>7984738c-0c4c-4387-8bf8-18e8e1b93081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>3eef3a09-2557-495e-8f58-5aeaf557f734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/en/news-and-media/contact-us/forms/employees' and @title = 'Contact form']</value>
      <webElementGuid>19b62f7d-2f48-4f57-ab32-6c82f15dcba8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
