<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone number_body_0ctl07txtPhone</name>
   <tag></tag>
   <elementGuidId>219c894b-728e-4d37-8f73-f8cf0d8a6691</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtPhone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPhone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b71aa2d1-c2fd-487d-a94a-03671c8f8303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>body_0$ctl07$txtPhone</value>
      <webElementGuid>0abf2d86-ea2a-41ea-b0f7-7974397b5c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0a4c3b1d-bf2c-411a-a95a-a36dc552dfd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPhone</value>
      <webElementGuid>3e89b8cb-a9a3-48c8-9705-20961e1f7f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phone number</value>
      <webElementGuid>b05245ae-f6e6-42ab-8db0-c0da0c9cd0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPhone&quot;)</value>
      <webElementGuid>78f6ab51-0ee0-4a88-927a-572016209e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/UI/Page_Contact Us  The Este Lauder Companies Inc/iframe_Employee Query_form-frame</value>
      <webElementGuid>2f2d97f0-a9e2-49f6-91ef-0272acbf6507</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPhone']</value>
      <webElementGuid>db67bae2-7a88-4f52-82fe-6c1cb6579bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MainForm']/div[3]/div[2]/div[2]/div[4]/div/input</value>
      <webElementGuid>bed019de-d24d-4be3-9987-70c49baea9b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>104715a2-bb87-41f4-9127-35aa39cab99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'body_0$ctl07$txtPhone' and @type = 'text' and @id = 'txtPhone' and @placeholder = 'Phone number']</value>
      <webElementGuid>dd10c43e-19e8-4af9-89da-6f852d11ca5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
