<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OK_body_0ctl07Submit</name>
   <tag></tag>
   <elementGuidId>f90837c8-ee8f-4109-89e5-62a22894e894</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#body_0_ctl07_Submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='body_0_ctl07_Submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e526d9cb-906d-4481-85b2-7716e692d4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>630535d8-8403-4c65-9368-1172cd43f4e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>body_0$ctl07$Submit</value>
      <webElementGuid>570565f0-5826-423e-94d3-66c597fccacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SUBMIT</value>
      <webElementGuid>9bffa5b7-bfff-4d62-b1a5-fea9f2bceae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;body_0$ctl07$Submit&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>ff720a3a-7bf0-445e-9d1d-ab9dcbf94046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>body_0_ctl07_Submit</value>
      <webElementGuid>e1c86c7a-2c4a-4961-9fe8-fb5fd5b9d9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit-button</value>
      <webElementGuid>05f9e3d2-611e-4ce4-923c-820a22968c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body_0_ctl07_Submit&quot;)</value>
      <webElementGuid>46c10c32-b15a-49ac-bb03-aeb73e7a05a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/UI/Page_Contact Us  The Este Lauder Companies Inc/iframe_Employee Query_form-frame</value>
      <webElementGuid>17c22f43-2e39-402d-abca-92278a62aeba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='body_0_ctl07_Submit']</value>
      <webElementGuid>9055c631-4168-4086-9920-0e617dbf6fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MainForm']/div[3]/div[2]/div[3]/div/div[5]/input</value>
      <webElementGuid>b2b8c1f7-056d-4c3e-882e-a50cab336130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>57341b86-d327-4ac3-9caf-ff4169969bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'body_0$ctl07$Submit' and @id = 'body_0_ctl07_Submit']</value>
      <webElementGuid>e38fd59d-5014-4560-ad2f-335d22c75d3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
