<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Location_body_0ctl07txtStateEmea</name>
   <tag></tag>
   <elementGuidId>fde6a138-2887-4869-be26-ca82edb17a8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtStateEmea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtStateEmea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6893cdf-8360-422a-a19a-118f18746fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>body_0$ctl07$txtStateEmea</value>
      <webElementGuid>6ca14dc6-8a8f-4414-b38c-efae9a0137c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>055924e8-0ea0-4016-888c-80c8f0a38693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtStateEmea</value>
      <webElementGuid>bff6e50b-17d3-4012-b788-e507f44ea610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Location*</value>
      <webElementGuid>19317ff8-39a0-4bc9-9fc3-bba7e27518a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required-field</value>
      <webElementGuid>da33b2f0-b822-4d71-9633-39a453357651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtStateEmea&quot;)</value>
      <webElementGuid>2ea62316-a9a5-48a4-8200-eb5263775d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/UI/Page_Contact Us  The Este Lauder Companies Inc/iframe_Employee Query_form-frame</value>
      <webElementGuid>5b28fe89-9deb-4733-8a51-74c919470edc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtStateEmea']</value>
      <webElementGuid>b139fbee-761d-4705-a7f6-26e9d63af5f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MainForm']/div[3]/div[2]/div[2]/div[3]/div/input</value>
      <webElementGuid>7254479e-ce6f-4cf0-9109-8863563a11e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/div/input</value>
      <webElementGuid>dfea080b-34c3-4da5-ae38-d9278eb1e45a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'body_0$ctl07$txtStateEmea' and @type = 'text' and @id = 'txtStateEmea' and @placeholder = 'Location*']</value>
      <webElementGuid>5fb5a9ed-c233-4b1e-be13-c48b1b05a211</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
