<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_body_0ctl07txtLNameEmea</name>
   <tag></tag>
   <elementGuidId>73dae9cb-a862-41a9-9d07-ef17a9aea439</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtLNameEmea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLNameEmea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d9ad515-3769-4227-a573-d77683346597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>body_0$ctl07$txtLNameEmea</value>
      <webElementGuid>f365e239-862b-428c-8171-38b13faa6f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0be4f5df-db1a-4327-be67-d5677f3e4386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLNameEmea</value>
      <webElementGuid>fb615d7c-bb82-4488-b80f-67f2e2759658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name*</value>
      <webElementGuid>b5779c20-d8ef-484e-86c9-2eb9e0e4f813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required-field</value>
      <webElementGuid>c453b491-cd20-4f43-9bd3-0b1a203e8313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLNameEmea&quot;)</value>
      <webElementGuid>11fa8b27-c02b-4835-a010-556eaaf75348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/UI/Page_Contact Us  The Este Lauder Companies Inc/iframe_Employee Query_form-frame</value>
      <webElementGuid>b0d8c844-54a8-46d2-9df1-f0383c221e54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLNameEmea']</value>
      <webElementGuid>650373f4-50e9-406e-b3f7-6ddc3dd6f31e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MainForm']/div[3]/div[2]/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>65c440b5-eae9-48f0-8be9-f51f722e1b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>94d4ff33-d437-4e80-abfe-f52dc6643cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'body_0$ctl07$txtLNameEmea' and @type = 'text' and @id = 'txtLNameEmea' and @placeholder = 'Last Name*']</value>
      <webElementGuid>09e832a9-c724-466e-a3fe-2a59bb8fa778</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
