<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Message Subject_body_0ctl07txtMsgSubEmea</name>
   <tag></tag>
   <elementGuidId>c1da3347-4499-4392-be8a-831c8e2866e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtMsgSubEmea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtMsgSubEmea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06e88614-0b90-463d-b3a6-fbe7b15ecc7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>body_0$ctl07$txtMsgSubEmea</value>
      <webElementGuid>9e9f6fc6-5e98-441d-b6a4-9ef8c1c0a21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e9ab7641-b974-493c-9638-87842fad39e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtMsgSubEmea</value>
      <webElementGuid>5cea6dd9-4959-4c04-8e68-501fbc5001d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Message Subject*</value>
      <webElementGuid>88e67b53-01ef-47e6-8090-e70f24614581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required-field</value>
      <webElementGuid>31c23230-eb65-4066-aad9-438f50ca8b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtMsgSubEmea&quot;)</value>
      <webElementGuid>d49dcc81-8860-4a95-936f-eb1e5cb8f73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/UI/Page_Contact Us  The Este Lauder Companies Inc/iframe_Employee Query_form-frame</value>
      <webElementGuid>c5ef8a9b-40c1-40c7-a937-032cf5d09236</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtMsgSubEmea']</value>
      <webElementGuid>902810bd-1a71-447d-9ad3-27e998eb865d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MainForm']/div[3]/div[2]/div[2]/div[5]/div/input</value>
      <webElementGuid>26b06754-f1c9-45f5-93eb-b31566273612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>13d8a083-45d7-4148-94e7-3814e5c3e0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'body_0$ctl07$txtMsgSubEmea' and @type = 'text' and @id = 'txtMsgSubEmea' and @placeholder = 'Message Subject*']</value>
      <webElementGuid>75207ebf-0125-45eb-b3bb-7a449c77be05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
