<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email address_body_0ctl07txtEmailEmea</name>
   <tag></tag>
   <elementGuidId>5a6ab8d3-fcec-4c93-8c5d-cfd02e55c831</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtEmailEmea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtEmailEmea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0655c33-411a-4679-aaa3-57a37e0d10bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>body_0$ctl07$txtEmailEmea</value>
      <webElementGuid>fd0b7767-33c1-4952-91eb-e23bb940e05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c759802-12ba-4c46-b20a-8aeef660b610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtEmailEmea</value>
      <webElementGuid>568743b5-4ab6-46fd-9d9a-8f26535f1573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email address*</value>
      <webElementGuid>25f4c679-a715-4e01-9262-6c6bc30ec0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required-field</value>
      <webElementGuid>a9baa026-cabb-44d8-bc8a-766a6c73e508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtEmailEmea&quot;)</value>
      <webElementGuid>0f962601-2471-41ff-b090-d5057f204b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/UI/Page_Contact Us  The Este Lauder Companies Inc/iframe_Employee Query_form-frame</value>
      <webElementGuid>7b2184f9-d165-405a-a033-1ea0156fa6ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtEmailEmea']</value>
      <webElementGuid>f9b7c468-553b-4538-9194-51488ac73c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MainForm']/div[3]/div[2]/div[2]/div[3]/div[2]/input</value>
      <webElementGuid>70fac533-abfd-491c-8b5c-fc70a03f0ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]/input</value>
      <webElementGuid>074e888b-14a9-44e2-a812-9f44f5c991de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'body_0$ctl07$txtEmailEmea' and @type = 'text' and @id = 'txtEmailEmea' and @placeholder = 'Email address*']</value>
      <webElementGuid>83a47527-8df0-4ac0-b999-761415410801</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
