<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_body_0ctl07txtFNameEmea</name>
   <tag></tag>
   <elementGuidId>20dc6b93-3f6e-4990-960a-1b899438d4b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtFNameEmea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtFNameEmea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c88863db-0f6e-42e7-b267-d5a19152dc0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>body_0$ctl07$txtFNameEmea</value>
      <webElementGuid>794ada3c-61e7-4ca0-9cda-e181203e751a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>475da499-477e-43f1-81a9-a1ee9eb9ffbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtFNameEmea</value>
      <webElementGuid>8b592cdc-eab2-46e7-9f6e-27798b5b3712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name*</value>
      <webElementGuid>9ca5696f-2a06-432b-a6dd-bbef0010ff06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required-field</value>
      <webElementGuid>4e1e467b-c3dd-4dbc-8c91-210b32913c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtFNameEmea&quot;)</value>
      <webElementGuid>a63d28c9-28b8-45c1-a681-16d509c0924b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/UI/Page_Contact Us  The Este Lauder Companies Inc/iframe_Employee Query_form-frame</value>
      <webElementGuid>ed4f3875-59b9-45f1-b29f-e187e07b8457</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtFNameEmea']</value>
      <webElementGuid>3743170a-6820-4cbd-b5af-90993201d9dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MainForm']/div[3]/div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>33133c95-7d4a-4746-adaa-8fb275d78229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>2a6d5e4e-d16e-44e7-897d-f4e57b53a9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'body_0$ctl07$txtFNameEmea' and @type = 'text' and @id = 'txtFNameEmea' and @placeholder = 'First Name*']</value>
      <webElementGuid>0914af7a-73b4-4d19-8838-7feeb23873e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
