<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_YOUR MESSAGE_body_0ctl07txtMsgBodyEmea</name>
   <tag></tag>
   <elementGuidId>75ada717-8811-41f4-bde3-c0fde7673a2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtMsgBodyEmea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtMsgBodyEmea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>daa95f62-f5d4-48c6-854b-bd4247f3d187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>body_0$ctl07$txtMsgBodyEmea</value>
      <webElementGuid>20f4745d-d687-4efe-a7a6-73093d3f7bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>18a05ccc-ad5c-467b-a94b-1cf1269e2f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>7f9e211c-f936-4812-9e00-f5e11d524ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtMsgBodyEmea</value>
      <webElementGuid>8c7d76f5-ea98-4edf-ad30-4b7008502e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>YOUR MESSAGE*</value>
      <webElementGuid>681a55bf-1083-4e3c-93ae-c20fb594c71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required-field</value>
      <webElementGuid>24a654f4-46fb-47c1-b9a2-d6243c144c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtMsgBodyEmea&quot;)</value>
      <webElementGuid>5c35f05d-9526-4852-888e-bac1aff5700a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/UI/Page_Contact Us  The Este Lauder Companies Inc/iframe_Employee Query_form-frame</value>
      <webElementGuid>62015108-0006-4c05-9221-b1445554fa6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtMsgBodyEmea']</value>
      <webElementGuid>1992b66f-7020-4fbf-aeaa-b731545fd6af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MainForm']/div[3]/div[2]/div[2]/div[5]/div[2]/textarea</value>
      <webElementGuid>6ffc254f-ac2f-4a79-a1b1-9b855b61e2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>fa795ab2-cb13-4e46-a0b8-293eed73398f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'body_0$ctl07$txtMsgBodyEmea' and @id = 'txtMsgBodyEmea' and @placeholder = 'YOUR MESSAGE*']</value>
      <webElementGuid>516a27f0-0781-428b-80b2-1ad1045f24ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
